sensor_fusion:
  sensor_fusion:
    ros__parameters:
      base_link: "base_link"
      correlation_matrix:
        row0: [100.0, 0.0, 0.0]
        row1: [0.0, 100.0, 0.0]
        row2: [0.0, 0.0, 100.0]
      twist:
        link: "twist_link"
        update_time: 0.05
        noise: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
      pose:
        link: "pose_link"
        update_time: 0.1
        noise: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
      imu:
        link: "imu_link"
        update_time: 0.01
        accelerometer_random_walk_bias: [1e-6, 1e-6, 1e-6]
        gyroscope_random_walk_bias: [1e-6, 1e-6, 1e-6]
        accelerometer_noise: [1e-6, 1e-6, 1e-6]
        gyroscope_noise: [1e-6, 1e-6, 1e-6]
        correlation_noise: [1e-6, 1e-6, 1e-6]