# Tempos de amostragem e atualização (em segundos)
update_times:
  imu: 0.01
  dvl: 0.1
  slam: 0.1

# Parâmetros de ruído e bias dos sensores
sensors_noise:
  accelerometer_random_walk_bias: [1e-6, 1e-6, 1e-6]
  gyroscope_random_walk_bias: [1e-6, 1e-6, 1e-6]
  accelerometer_noise: [1e-6, 1e-6, 1e-6]
  gyroscope_noise: [1e-6, 1e-6, 1e-6]
  corr_noise: [1e-6, 1e-6, 1e-6]
  dvl_noise: [1e-6, 1e-6, 1e-6]
  slam_noise: [1e-6, 1e-6, 1e-6, 1e-6, 1e-6, 1e-6]
  corr_t: [1.0, 1.0, 1.0]
